### ISSUE TITLE
BUG: Recent Posts (Broken) and Home (not correct)

### ISSUE THREAD

**Issue by condio** [pacollins/hugo-future-imperfect-slim#130]
# Bug Report
## Describe the bug

Even on a clean download of the example site, recent posts does not work. In addition, the homepage acts like the /blog/page and shows a number of posts instead of only the newest post.

Looking at your screenshots, this should be working. Perhaps this broke in a recent merge?

## To Reproduce

1. Download this project as a ZIP.
2. UnZip
3. Use Example Site as test site
4. Create themes folder
5. git clone https://github.com/pacollins/hugo-future-imperfect-slim.git into the themes folder
6. hugo server

## Expected behavior

1. Recent Posts should show up to 5 recent posts as a defaut per the config.toml
2. Shouldn't the homepage be a single post vs mirroring the blog page?

## Screenshots

https://themes.gohugo.io/theme/hugo-future-imperfect-slim/
See your example site. The recent posts works here, BUT the homepage appears broken.

## Environment

 - **Hugo Version:** v0.67.0/Extended darwin/amd64
 - **Browser and Version:** FireFox v74.0 (64bit)
 - **Platform:** Desktop Mac
 - **Link to Project:**

## Additional context

I tried reading through all of the old issues/bugs and didn't see anyone mention these two items, so I apologize if it's a stupid question/issue.

Thanks.

**Comment by pacollins** [comment]
1. Recent posts in the sidebar seem to be working as intended on both the example site you linked and my local site. I don't see the error here.
2. The home page has always been a collection of posts. This is a commonality among almost every website in the world.

**Comment by pacollins** [comment]
Thanks for pointing this out - after further testing these are, in fact, bugs related to #122, which reduced specificity in the theme to give more power to the users. We removed `type="post"` from all exampleSite pages, but the sidebar (your first bug) still uses this as a way to pull recent posts. See below.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/6318d204847029e9fb40ae2fe69fb50c52c19084/layouts/partials/site-sidebar.html#L18

For the second bug, we needed to remove this line from the `config.toml` so that Hugo would determine the main pages.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/6318d204847029e9fb40ae2fe69fb50c52c19084/exampleSite/config.toml#L15

I will work on a patch later tonight.

**Comment by condio** [comment]
You're example site does work perfect for the recent posts. Just the current code does not.

I just did a fresh test: (perhaps I'm doing something dumb)
1. cd desktop
2. git clone https://github.com/pacollins/hugo-future-imperfect-slim.git
3. extract "exampleSite" from folder to Desktop
4. create "themes" folder under "exampleSite"
5. copy the cloned theme to the new "themes" folder
6. hugo server

That should in theory work, right?
Here's the code.
https://github.com/condio/hugo-future-imperfect-slim-issue

**Comment by condio** [comment]
Thanks for confirming and no rush at all. Thanks for working on this project and responding so quickly.

**Comment by pacollins** [comment]
I have fixed the initial issue here, which was a bug.

The new issue you have discovered has to do with how the general pagination was built with the original version of the theme. Good catch. I will open a separate issue with this.
