### ISSUE TITLE
FEATURE: Hide "Recent Posts" on Mobile/SingleView

### ISSUE THREAD

**Issue by condio** [pacollins/hugo-future-imperfect-slim#134]
# Feature Request

## Is your feature request related to a problem?

When viewing the site on mobile, you will view all of your posts on the main page, then scroll through a redundant list of "Recent Posts", then get to the small about section. It would be nice if we could hide the recent posts sidebar when in single column view.

- Recent Posts is great in the sidebar on a Desktop because you can quickly jump to a post, but it's redundant on Mobile and basically ends up duplicating content.

I tried to resolve this by adding    hideWhenSingleColumn  = true    but this did not work as you'd probably expect.

## Solution

Can we add  hideWhenSingleColumn  = true  to the   [params.sidebar] also? It works great for   [params.intro] and it would solve this issue.

**Comment by pacollins** [comment]
I see what your saying. There is some nuance to this because the sidebar and the homepage can actually populate with different posts. Additionally, the sidebar shows when you are within a page.

If someone is interested in making this PR, my recommendation would be to only hide it on the homepage and *maybe* the post directory page. It should exist everywhere else, where there is no redundancy.

**Comment by pacollins** [comment]
[We could possibly change it to related content.](https://gohugo.io/content-management/related/#configure-related-content)
