### ISSUE TITLE
BUG: Does not work

### ISSUE THREAD

**Issue by neodigm** [pacollins/hugo-future-imperfect-slim#135]
# Bug Report
## Describe the bug

Installed theme as per instructions and nothing.
Installed other theme and it works.

baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-future-imperfect-slim"

## Environment

 - **Hugo Version:** [e.g. 0.46]
 - **Browser and Version:** [e.g. Chrome 74.0.3729.108]
 - **Platform:** [e.g. Desktop/Mobile]
 - **Link to Project:**

**Comment by pacollins** [comment]
I'm not sure what issue you are having since you didn't give enough information, but since the [demo site](https://themes.gohugo.io/theme/hugo-future-imperfect-slim/) is working, there is no evidence that the theme as a whole is not work. The team that maintains the demo site get daily error reports from themes that are not working.
