### ISSUE TITLE
BUG: Page extends beyond view port on small devices

### ISSUE THREAD

**Issue by weltruf** [pacollins/hugo-future-imperfect-slim#147]
i have the same issue. When viewed on mobile device then i see just part of the site or have to zoom out. I even reverted back to the original config.tofl but it did not help. Seems to have something to do with the blogpost content itself. 
You can see this site of another guy who obviously has the same problem but seems not to have noticed it yet: https://jhonmanuncia.me/blog/
![Screenshot buggy future imperfect slim](https://user-images.githubusercontent.com/53140153/84366299-eca5eb80-abd2-11ea-910b-03b58b506dc0.png)

**Comment by pacollins** [comment]
So I am missing quite a bit of information since you chose to not use the issue template...

Ultimately, the visual issue is in the header, but this is not reproduced locally for me.

That being said, please:

1. Confirm you are using the most up-to-date version of the theme.
2. Confirm you are using the most up-to-date version of Hugo Extended.
3. Provide a link to a repo where this is an issue, *or* a sample markdown file which causes the issue.

**Comment by weltruf** [comment]
Hi Patrick,
yes, i cloned your repo 3 days ago.
yes, i installed Hugo Extended a few days ago.
I did not alter the CSS or SCSS files at all.
If I knew which markdown file causes the issue, i would have removed it
already. But I discovered that switching off the "touch emulation" button
in the firefox developer mobile view removes this erroneous display. So it
might be hidden in this "touch" code.
Can you please confirm that the website of the other instance of this
template i linked in the bug report is rendered completely normal on your
phone ? I tried it on 2 phones and on the emulator and it was not normal.
Thank you and kind regards,
Ole

Am Do., 11. Juni 2020 um 16:57 Uhr schrieb Patrick Collins <
notifications@github.com>:

**Comment by pacollins** [comment]
I should be clearer. When loading the example site on `localhost:1313`, I can not reproduce this error (with or without touch enabled). When I load the site you linked via desktop and mobile, I can reproduce this error.

If I had a markdown file for [this page](https://jhonmanuncia.me/blog/gaming/pokemmo/hoenn-walkthrough-03/) - which would be `content/blog/gaming/pokemmo/hoenn-walkthrough-03.md` - I would be able to load it on the example site and better troubleshoot the issue.

**Comment by weltruf** [comment]
Hi,
good to know that you CAN reproduce the error.
The site i linked and you linked now, too, this site does not belong to me,
that is why i cannot provide you with a markdown file.
But I had the same issue with this Hugo theme when i set up my blog ! That
is why i searched for other people who are using this template for to see,
if they have the same problem. Apparently, they do have.
Of course, the first blog i found was your personal blog. You wrote a good
article, but it is ONLY ONE article. I assume that the problem appears if
you have more than one article, lets say five articles/ blogposts.
So the only thing I can do is I suggest that you produce some more articles
and see, if you get this bug, too. Have you heard this bug from other
users, too ?
I do not know why it does not happen in the example site. That is true, the
example site renders normally, as long as i can remember.
Kind regards,
Ole

Am Do., 11. Juni 2020 um 20:17 Uhr schrieb Patrick Collins <
notifications@github.com>:

**Comment by pacollins** [comment]
I do not test the theme with my personal site, I test it with the demo you see on the Hugo Themes site, which has four articles. The error that is causing the issue is specific to individual articles, not the number of total articles, otherwise it would be reproduced on the demo site. That is why I would need a markdown file that *is* producing the error so I could track it down.

**Comment by twatzl** [comment]
Hi, 
I just found this issue and I have the same problem on my page as well. 
https://twatzl.eu/

I cannot reproduce the issue on desktop (not even with developer tools set to smartphone size). However I asked a couple of people and all have the issue when viewing my site on mobile.

Is it possible that the issue is related with featured post images? Because your demo page does not have featured post images, while my site has them and also the other site has them.

**Comment by weltruf** [comment]
as far as i know, i did not use featured post images and had the same
problem with my blog but i discovered that it gets a little better when you
disable "touch simulation" in developer mode, however, not completely fine
on twatzi.eu

Am Mi., 17. Juni 2020 um 22:51 Uhr schrieb twatzl <notifications@github.com

**Comment by pacollins** [comment]
@twatzl - The demo site does not have featured images, but the exampleSite articles do. When I test this locally with the exampleSite articles, I do not have the error.

Can either of you use `hugo server` on the [`exampleSite` contents](https://github.com/pacollins/hugo-future-imperfect-slim/tree/master/exampleSite) and check `localhost:1313` and confirm that you do or do not see the error there? We have already established that we can see it on both your sites, we cannot see it on my site, but we have not verified `localhost:1313` with the default files. This will help with finding the issue.

**Comment by pacollins** [comment]
Correction: I can see it on with the exampleSite, but it is erratic. Will be difficult to track down...

**Comment by pacollins** [comment]
I think I found it, though I don't know why it is happening `#site-intro` is going past the view width. Add `max-width: 100vw;` and confirm that fixes it. I don't know that this is the ultimate solution, but the issue is at least found.

**Comment by pacollins** [comment]
Quadruple posting to keep you guys up-to-date.

Upon further investigation, I think that the issue is to be due to a buggy `css` interaction due to the level of specificity in the `main.scss` file - hence why it was such a erratic bug. Because of this, I am simply going to expedite the task that was started in #122 to reduce specificity at the theme level and refactoring the `scss` file. By doing this, I should be able to better located and adjust the problem. As of this moment, I have refactored through the `Theme Grid` portion of the file, which ends at line 982.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/assets/scss/main.scss#L982

Once I have refactored everything, I will make a PR. While we are doing this, it would be great if people could hunt any other weird style idiosyncrasies so we can try to fix them now. I trust that each of you will be open to reviewing the PR as well! :smile:

**Comment by pacollins** [comment]
Fun stuff... I have narrowed it down to three totally separate issues (so far), which is why it has been so erratic.

- `table` was not designed well enough for the smallest screens. It works well from medium and up. *This will just need to be re optimized for the smallest screen type.*
- `reCAPTCHA` for Staticman *also* doesn't work well for the smallest screens. *This is an easy hack fix by forcing it to be `0px wide`, but it will still present itself as full width (which works visually as well as functionally).*
- The biggest culprit so far is the `stats/tags/categories` area at the bottom of the post. If you have a longer tag, it causes the page to stretch. *This will have to be entirely reworked. The simplest solution is to remove the fancy animation and either show all tags, or truncate it at 3 or so.*

**Comment by twatzl** [comment]
Thanks for all your effort. Let me know once you have a fix then I will roll out the changes on my blog. Will take about a week once the changes are available.

**Comment by pacollins** [comment]
@twatzl @weltruf - See the new PR. Its rather large with lots of change, but I would venture to guess that the vast minority will be affected.

**Comment by twatzl** [comment]
Hi, I tried to upgrade, however there are still some open points for me at the moment (see my comments in the PR), which means I have postponed the update. Since I cannot reach my test system from a phone to verify this issue it will have to wait for the time being.

Will let you know once I could test it.

**Comment by twatzl** [comment]
Seems to work now with the new PR 👍 
you can test it at https://twatzl.eu/ (just deployed the latest commits from the PR there)
