### ISSUE TITLE
Question: Staticman Comments Not Loading Github Pages

### ISSUE THREAD

**Issue by pra-dan** [pacollins/hugo-future-imperfect-slim#152]
Hi, I tried to add comments to my hugo site using staticman and it works now. What does it mean by "...displayed after it is reviewed" ? 

I have also tried to instead use [utterances](https://github.com/apps/utterances/installations) but I think there is no support for that yet. Please suggest. @VincentTam @pacollins

**Comment by pacollins** [comment]
It looks like your `baseurl` is wrong in your `config.toml` so things aren't linking up quite right.

**Comment by pra-dan** [comment]
But the comments aren't visible in the site...
 @pacollins You have helped me a lot. Thank you very much :)

**Comment by pacollins** [comment]
Because Hugo is a static site generator. Any time you add new content, you
have to rebuild the site. Comments are content.

Remember, your website is flat html not dynamic html.

There could potentially be an issue beyond this, but you would need to
fetch your comments locally and rebuild the site before you could determine
that. If you want comments to appear immediately, you should use a build CI
like netlify, or a server-based service like Disqus.

**Comment by pacollins** [comment]
I am renaming this because it has lost the focus of the title. If you have solved the issue, please close the issue. If you would still like Utterance support, please open another issue.
