### ISSUE TITLE
BUG: Previous/next for blog inconsistent with pagination

### ISSUE THREAD

**Issue by kdbruin** [pacollins/hugo-future-imperfect-slim#163]
# Bug Report

## Describe the bug

The previous/next buttons underneath a blog are in reverse order compared to the pagination. With pagination the left button goes to the previous page (more recent posts) and the right button to the next page (older posts). Underneath a blog page the left button will go to the next (older) article and the right button goes to the previous (newer) article.

## To Reproduce

Visible when multiple blog posts are available that generate at least 3 pages.

## Expected behavior

The left button underneath the blog should go to the newer article, the right button to the older article.

## Screenshots

On the blog index page the order of articles is shown including the previous/next buttons:

<img width="712" alt="Screenshot 2020-07-14 at 07 16 46" src="https://user-images.githubusercontent.com/3851711/87387059-3606a380-c5a2-11ea-8ff6-06912f12cccd.png">

The next image shows the buttons underneath the middle article. The order does not match that of the index page:

<img width="729" alt="Screenshot 2020-07-14 at 07 17 02" src="https://user-images.githubusercontent.com/3851711/87387136-60f0f780-c5a2-11ea-885d-c7b0d145040a.png">

## Environment

 - **Hugo Version:** [0.73]
 - **Browser and Version:** [Safari 13.1.1]
 - **Platform:** [Desktop + Mobile]
 - **Link to Project:**

**Comment by pacollins** [comment]
I understand what you are saying, but I think it is a linguistic issue.

When you are on a list of pages, you are going to the *next* page (because there is only one page as an option).

When you are on a single post, you are going to the *previous* post if you are going back in time (because posts are time-based).

Here are the relevant templates for the theme.

For Single Pages:
https://github.com/pacollins/hugo-future-imperfect-slim/blob/5f7d838034b42a215092addc7a6319ac7ee204da/layouts/partials/pagination.html#L1-L9

For List Pages:
https://github.com/pacollins/hugo-future-imperfect-slim/blob/5f7d838034b42a215092addc7a6319ac7ee204da/layouts/_default/pagination.html#L1-L8

----

That being said, I will look at some other themes to see what they do.

**Comment by pacollins** [comment]
After looking at this further, I agree.

**Single page pagination left should go to newer posts while right should go to older posts as it does with the list pagination.**

I will include this in #154, which I hope to merge by the end of this week.
