### ISSUE TITLE
FEATURE: Add authors page

### ISSUE THREAD

**Issue by pylenin** [pacollins/hugo-future-imperfect-slim#19]
# Feature Request
**Is your feature request related to a problem? Please describe.**
One important thing missing from this blog is the author section.

**Describe the solution you'd like**
We are a team of Python developers and we would like to have designated author section for each of our authors.

**Additional context**
Is it possible to add the authors page functionality to this amazing theme?

**Comment by pacollins** [comment]
Can you explain a little more? Do you mean just a "Staff - About Us" Page, or individual staff pages?

**Comment by pylenin** [comment]
Something similar to categories and tags. So along with those taxonomies, is it possible to add a similar feature for authors?

If one clicks on an author, it takes them to an author page with their bio and filtered blogs that they have written. Does it make it clear?

**Comment by pacollins** [comment]
[Hugo supports custom taxonomies](https://gohugo.io/content-management/taxonomies/), but that would be a little too niche for the theme to support (in my opinion). I wouldn't be opposed to helping with the development, answering questions, and offering it as an "add-on," but I don't think it should be part of the master to avoid bloat.

Due to this, I will close this issue, but feel free to keep your conversation going or link the issue to your personal version of the theme.

**Comment by reiner** [comment]
would it be possible to just somehow filter authors such as “categories“ and “tags“. So visitors could see a list of all articles written by a specific author? Thank you!

**Comment by pacollins** [comment]
You would need to create a new taxonomy (refer to the link above) for authors.
