### ISSUE TITLE
ENHANCEMENT: Change to natural Japanese

### ISSUE THREAD

**Issue by yyh-gl** [pacollins/hugo-future-imperfect-slim#203]
It's a great theme for me.
Thanks for your work!

This is the enhancement suggestion, not a bug.

# Bug Report

## Describe the bug

I think it's unnatural to translate about as "約".
(I'm Japanese and I've never seen this kind of translation.)

## Expected behavior

If "About" represents introducing yourself, "自己紹介" is better.
Or, "About" is introducing site, "概要" or "本サイトについて" is better.

If "About" has some roles, translating is so hard.
In this case, I think that it's better to use the English language without translation.
(For making the rules consistent, I would prefer not to translate for "Blog", "Category", "Tag" and "Contact" as well.)

**Comment by VincentTam** [comment]
ありがとうございます！  If you think that's not working the way you expect it should, you may call it a bug.  Thanks for your suggestion.  I appreciate your explanation about the two possible translations.

Would be mind submitting a PR, so that you get the credits for your contribution?  I wonder if "概要" would work here?

https://github.com/pacollins/hugo-future-imperfect-slim/blob/2693d913cd78a8453fc263f709f5ce15e8014f23/i18n/ja.toml#L15-L19

In the ideal case, both possibilities were catered, and user could choose what they want through customizing the above field, just like adjusting the height of an armchair: for a personal page, one might want "自己紹介"; for a project page, one might want "概要" or "本サイトについて"—but that's too much development work for a translator.

P.S. I can only read the Kanzi (漢字), but very often the ideographic characters are used in a different way than my native language, so I let you to decide the best.

**Comment by yyh-gl** [comment]
> In the ideal case, both possibilities were catered, and user could choose what they want through customizing the above field, just like adjusting the height of an armchair

Make sense:)

I think "本サイトについて" is best and it's enough for users to customize it if they are curious about it.
"本サイトについて" means "About this website".

> Would you mind submitting a PR, so that you get the credits for your contribution?

OK, I will work it.

**Comment by yyh-gl** [comment]
Work is done.
https://github.com/pacollins/hugo-future-imperfect-slim/pull/204

**Comment by VincentTam** [comment]
> I think "本サイトについて" is best and it's enough for users to customize it if they are curious about it.
> "本サイトについて" means "About this website".

Agreed.  This works for personal sites also.  :+1:
