### ISSUE TITLE
BUG: Twitter card doesn't show the feature image

### ISSUE THREAD

**Issue by Jubijub** [pacollins/hugo-future-imperfect-slim#41]
# Bug Report
## Describe the bug
Twitter card doesn't show the feature image

## To Reproduce

1. write an article with the feature image declared like this
featured = "2019-07-Expatriation-2-Arriving-in-London.jpg"
featuredalt = "London from the 'London Eye'"
featuredpath = "date"

[twitter]
  image = "https://www.jubi.io/img/2019/07/2019-07-Expatriation-2-Arriving-in-London.jpg"
  image_alt = "London from the 'London Eye'"

## Expected behavior
When posting on Twitter, I would expect the TwitterCard to show the picture
Upon inspecting the source code, I expect to find a <meta name="twitter:image> or og:image tags (cf the [specification)](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup.html)
Upon using Twitter card validator, the image should be found

## Actual behavior
The image feature is found, and does show up on the blog entry thumbnail, and as the hero image on the blog post itself.
![Screenshot from 2019-08-03 20-33-16](https://user-images.githubusercontent.com/1254368/62416200-0e872700-b62e-11e9-83af-2a82051b448e.png)
![Screenshot from 2019-08-03 20-34-00](https://user-images.githubusercontent.com/1254368/62416201-0e872700-b62e-11e9-9d3f-dc832cd4a01c.png)

The Twittercard shows the generic image
The twitter:image tag is nowhere to be found in the source code, which makes the validator fail to find the image

 - **Hugo Version:** : v0.55.6
 - **Browser and Version:** : Chrome Beta 76.0.3809.87 (Official Build) beta (64-bit)
 - **Platform:** : Linux (not platform dependant)
 - **Link to Project:** : https://jubi.io/blog/2019-07-expatriation-2-arriving-in-london/

## Additional context
The default partial code is [here](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html), and seems to support many ways of declaring the image. It also seems that the template calls this partial in `/themes/hugo-future-imperfect-slim/layouts/partials/head.html`
I suppose I am declaring the image wrong, but I don't know what is wrong.

**Comment by pacollins** [comment]
Thanks for catching this. We will need to look into it. If you have the chance, that would be awesome!

**Comment by pacollins** [comment]
After inspection, it looks like the original theme did not have it set up right by using [`featured` instead of `feature`.](https://gohugo.io/templates/internal/#twitter-cards)

If someone could check me, like @VincentTam, we are probably best to change them all to `feature` or `images` *or* we could just add a new front matter called `images` which would be solely for cards.

**Comment by VincentTam** [comment]
@pacollins I haven't tested, but from what I've understood, `featured` in this theme has two meanings: `layout: featured` and `class = "feautred"`.  Personally, I prefer setting a new front matter `images` so as to be consistent with Hugo's syntax, and refactor our template containing `feature*`.

**Comment by Jubijub** [comment]
It would be good to document how to use images, from multiple axis : 
- how to store the images (page bundle, img folder in /static, etc..) and how to update the front matter depending on which option is used
- what are the features for using images inside the template (so far I only use the built-in shortcode `figure` but it's not necessarily clear how to center images, etc... (I seem to recall the original theme had features for this, including an image gallery).
I am happy to help flesh out the doc, but I don't know go / hugo enough to build all of it on my own :(

**Comment by pacollins** [comment]
@VincentTam You mean change everything in the code base from `featured` to `images`? We could probably rig some backwards compatibility so that it doesn't break previous uses of "featured."

@Jubijub As of right now there are two options, just using the path, and using date. Date stores it as YEAR/MO/File.ext. As for the image centering and what not, fancy box is still a feature (image gallery), but the others I removed because they were buggy and redundant iirc.

**Comment by VincentTam** [comment]
@pacollins I wonder if one of the following backward-compatible approaches would work:

1. Copy parameter `featured` and append it to `images`.
2. Ask users to manually change the name of their resources in their page resources.  That' shouldn't be difficult.

**Comment by pacollins** [comment]
[Here](https://github.com/gohugoio/hugo/tree/master/tpl/tplimpl/embedded/templates) are the internal templates for Hugo. My initial assessment is that we should:

1. Remove [`meta name=description'](https://github.com/pacollins/hugo-future-imperfect-slim/blob/f0ec5ac57e6765ef2cf1cb4a2f585bfc1c1c5c6b/layouts/partials/meta.html#L3) since it is covered under [`_templates/schema.html`](https://github.com/gohugoio/hugo/blob/e88d7989907108b656eccd92bccc076be72a5c03/tpl/tplimpl/embedded/templates/schema.html#L2)
2. Change Archetypes to reflect [`images = [""]`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/archetypes/blog.md) and encourage it's use.
3. Adjust the [`featured` template](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/layouts/post/featured.html) to utilize `images` as the main source and using `featured` as a fallback.
4. In addition to adjusting to include `images`, update the `featured` template to produce a slideshow for up to six images, that would populate with the `images` array. This would be consistent with  [`_templates/schema.html`](https://github.com/gohugoio/hugo/blob/e88d7989907108b656eccd92bccc076be72a5c03/tpl/tplimpl/embedded/templates/schema.html#L8).

**Comment by Jubijub** [comment]
short term until those fixes are made, how are we supposed to declare images to make them visible in OpenGraph / Twitter cards ?

**Comment by VincentTam** [comment]
@Jubijub Recently, @<span>pacollins</span> and I have worked on issues like license, (missing) translations, [Staticman](https://staticman.net) nested comments (and bug fixes that I've spent two days on) and most importantly, empty home page in Hugo 0.57 (pinned by me).

I didn't write the code for this feature.  As you asked for a short-term workaround, excuse me for suggesting a *temporary* way by overriding the relevant partial layout in the repo for your own site followed by the injection of the relevant `<meta>` tag for `twitter:image` into the copied partial template.

Anyone is more than welcome to post a PR.

**Comment by Jubijub** [comment]
I fail to see the logic of your comment : if I knew how to post a PR on this, that would mean I know how image processing work in Hugo in conjunction with theme features, which would mean I would be able to answer my own question, or even better, fix my problem. Unfortunately I don't, which is precisely why I use a ready-made theme, because I don't know `go` or `html/template`.

I am thankful for all the work you are doing on this theme, but if you jump defensively on any bug comments I will simply stop submitting bugs and find a theme where the maintainers are nicer. I don't think it's unfair to ask whether there is a workaround or not (eg, something like declaring the pictures in a different way), and that doesn't imply I am expecting a perfect solution right now which would be unfair to you. Not all Themes users are necessarily capable of building or tweaking a theme (while doing a `git clone git@github.com:pacollins/hugo-future-imperfect-slim.git` is way more simple.) so you will have to be OK with the fact some people cannot fix the bug their reported.

_Show me the code_ has been known to be a very sure way to drive people out of the community. While I cannot code (in go), I can read code, do test, do documentation, report bugs, verify solutions, etc... Hell, I could maybe even be able to fix that bug, if I knew where to start (I know how to code, but in Java/Python).

**Comment by pacollins** [comment]
Short term solution:

Change all `.featured` of this file to `.images`.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/58c2de987481f7bb3d3d37500186c69db633efe8/layouts/post/featured.html#L1-L5

Change the front matter of your posts from `featured = ""` to `images = [""]`

This is exactly what I wrote out in the [comment above](https://github.com/pacollins/hugo-future-imperfect-slim/issues/41#issuecomment-520109708). Little, if any, knowledge of Go is required for this change, beyond the fact my comment provides enough links and documentation to fix the issue (barring the slideshow feature that would need to be implemented for multiple images).

While we do appreciate bug reports, it is important to understand priority. #71 _literally_ prevents the theme from working. #47 is an _ethical_ concern. Add the fact that this is a passion project for myself. I am a full time educator and school has just started back. Please understand that while this may be annoying, the theme works without it for the time being.

**Comment by Jubijub** [comment]
Thanks for the solution.
I am sorry I wasn't able to do this from your comments. I thought you were discussing how to fix the bug with other maintainers ("we should do"), I didn't realize this was the instructions for a workaround.

But I will say one thing about the priority bit : I don't think I forced any one of you to answer, I would have been completely fine with an answer "whenever you could", or even no answers.

I think you should both relax. This is an open source project that you are clearly maintaining on your free time, I don't think anyone has any expectations of an SLA. If I wanted an SLA, I'd learn how to do it myself, or I'd pay for professional services to fix it.  It's fine if you don't answer, or if you just say you don't have time for this now. 👍 
I also understand priorities, and indeed #71 and #47 are far more important. 
But you should be OK with people asking questions, especially until the documentation on both Hugo and the theme is more elaborated (which is something I can help with)

**Comment by VincentTam** [comment]
@Jubijub I wanted to answer you a few hours ago, but for some reasons I couldn't.

> I fail to see the logic of your comment : if I knew how to post a PR on this, that would mean I know how image processing work in Hugo in conjunction with theme features, which would mean I would be able to answer my own question, or even better, fix my problem. Unfortunately I don't, which is precisely why I use a ready-made theme, because I don't know `go` or `html/template`.

The organisation of my reply goes as follow:

- background: explain our recent work done on other features, so that others know that we are maintaining our themes.
- body: my personal rough suggestion.  Even though there's no responsibility in open-source licenses, I didn't want you (or other users) to spend hours on trying something that won't work.  It would be irresponsable for me, as a collaborator, to comment casually on code that I've never wrote or tested.
- final remarks: invitation for anyone to submit a PR
 
> I am thankful for all the work you are doing on this theme, but if you jump defensively on any bug comments I will simply stop submitting bugs and find a theme where the maintainers are nicer. I don't think it's unfair to ask whether there is a workaround or not (eg, something like declaring the pictures in a different way), and that doesn't imply I am expecting a perfect solution right now which would be unfair to you. Not all Themes users are necessarily capable of building or tweaking a theme (while doing a `git clone git@github.com:pacollins/hugo-future-imperfect-slim.git` is way more simple.) so you will have to be OK with the fact some people cannot fix the bug their reported.

You're asking for a short-term workaround, so I responded with one based on what I understand from Twitter's docs.  The first paragraph can be elaborated.  I simply wanted to say that we had spent time on other issues, and I begged your pardon for the time that your issue had remained unsolved.

> _Show me the code_ has been known to be a very sure way to drive people out of the community. While I cannot code (in go), I can read code, do test, do documentation, report bugs, verify solutions, etc... Hell, I could maybe even be able to fix that bug, if I knew where to start (I know how to code, but in Java/Python).

As your issue concerns any Twitter user**s** who wish tweet any page using this theme, I wrote to "anyone" actually.  That's supposed to be an invitation for other**s** to submit a PR.
