### ISSUE TITLE
BUG: What is the matter with add-on.js and add-on.css?

### ISSUE THREAD

**Issue by twatzl** [pacollins/hugo-future-imperfect-slim#87]
Hello, 

I was looking for the source of the issues why my browser was complaining that `add-on.css` and `add-on.js` have a MIME type mismatch. I read that this occurs when the file does not exist. And indeed those two files do not exist. However the documentation still lists them and they are also referred to in `partials/scripts.html` and `partials/head.html`.

So what is the matter with those files. Are the references forgotten references and should be removed or am I missing something?

I get the errors on the hugo live server as well as on my production system.

**Comment by twatzl** [comment]
https://github.com/pacollins/hugo-future-imperfect-slim/pull/88

**Comment by VincentTam** [comment]
@twatzl Nice catch!  We're working out these two files in #66.

**Comment by twatzl** [comment]
I just noticed the files exist in the exampleSite and quickly put a PR together. I was not expecting you to answer so quickly :D

**Comment by twatzl** [comment]
If you are already working on it you can just dump my PR.

**Comment by pacollins** [comment]
If I remember correct from the last time I looked at it, the browser *really* doesn't like that the files are empty with a comment at the top.

**Comment by VincentTam** [comment]
> If you are already working on it you can just dump my PR.

@twatzl In fact, this section in the site config has existed for long.

https://github.com/pacollins/hugo-future-imperfect-slim/blob/b055367ca22c34994e0bfaf1e32d5787e6fce191/exampleSite/config.toml#L15-L20

I've altered greatly the structures of both partial templates at commits 72629f7, 09155a6 and b055367, in response to @pacollins' request to get our Staticman JS script bundled with other JS scripts.

I appreciate your effort in making #88.  Even though your `static/*/add-on.*` has to be dumped, it seems good to add a section <del>in the README</del> to give a brief mention of `cssFiles` and `jsFiles` in the site config.  Since #84 is in progress, perhaps your edit might cause a merge conflict in the README file from a technical point of view, but most of its content is good.

> You can adapt this theme according to your preferences using your own JS or CSS code. To do this your can [edited the ... params in the site config].

Before I clicked "Commnt", @pacollins had commented, so would you mind editing the Wiki with the above quoted sentence?

Remarks: Looking back, I'm sorry for having complicated the commit history by 6449077, which would have been avoided if I had merged recent changes on the upstream `master` branch before actually working on the head of the `remove-cdn` branch.  I'll try my best to [keep Git history down](
https://discourse.gohugo.io/t/hugo-themes-donts/17714?u=vincenttam).

**Comment by twatzl** [comment]
Hey. Sorry for not responding for such a long time. I was quite busy at work and only had time this weekend to work on my blog again. What is the status? what needs to be done? Just the wiki entry?

**Comment by VincentTam** [comment]
> Hey. Sorry for not responding for such a long time. I was quite busy at work and only had time this weekend to work on my blog again.

Nvm.  We too.

>  What is the status?

#66, which deals with the add-on stuff, turns out to be more complicated than I've expected—I didn't know that the CSS load order matters. It seems that I've to take some courses about web development—some recommended Udemy, I'm thinking about 3W Academy.

> what needs to be done? Just the wiki entry?

The content of https://github.com/pacollins/hugo-future-imperfect-slim/pull/88/files#diff-04c6e90faac2675aa89e2176d2eec7d8 can go to the [Wiki's config.toml page section `.Site.Params`](https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml#siteparams).

**Comment by pacollins** [comment]
Fixed with #66
